KG_MASK = "<KNOWLEDGE_GRAPH>"
SUBJECT_MASK = "<SUBJECT>"
RELATION_MASK = "<RELATION>"
OBJECT_MASK = "<OBJECT>"
EOS_MASK = "<EOS>"

EMPTY_OBJECT = "NONE"

VALID_MASK = "<VALID>"
TRUE_FLAG = "TRUE"
FALSE_FLAG = "FALSE"